quarkus.application.name=uatz-server
quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=uatz
quarkus.datasource.password=uatz
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/uatz

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=uatz
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.issuer=uatz

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
