package br.com.uatz.server.exception;

/**
 * Chaves das mensagens de negócio. Cada valor precisa existir em
 * `src/main/resources/messages_pt_BR.properties`.
 */
public enum CloudMessage {

	/* @formatter:off */

	// Autenticação e usuários
	BOOTSTRAP_INDISPONIVEL,
	CREDENCIAIS_INVALIDAS,
	EMAIL_JA_EXISTE,
	PERFIL_NAO_ENCONTRADO,
	USUARIO_NAO_ENCONTRADO,

	// Cadastros
	CATEGORIA_NAO_ENCONTRADA,
	CATEGORIA_PAI_NAO_ENCONTRADA,
	CLIENTE_NAO_ENCONTRADO,
	PRODUTO_NAO_ENCONTRADO,

	// Fornecedores
	FORNECEDOR_NAO_ENCONTRADO,
	FORNECEDOR_INATIVO,
	PERFIL_FORNECEDOR_NAO_ENCONTRADO,
	USUARIO_FORNECEDOR_NAO_ENCONTRADO,
	EMAIL_FORNECEDOR_OBRIGATORIO,
	SENHA_FORNECEDOR_OBRIGATORIA,

	// Pedido de orçamento e distribuição
	PEDIDO_NAO_ENCONTRADO,
	REVISAO_SEM_ITENS,
	SITUACAO_NAO_ENCONTRADA,
	NENHUM_FORNECEDOR_ELEGIVEL,
	FORNECEDOR_NAO_VINCULADO_PEDIDO,
	FORNECEDOR_JA_RECUSOU_PEDIDO,
	FORNECEDOR_JA_RESPONDEU_PEDIDO,

	// Cotação
	COTACAO_NAO_ENCONTRADA,
	COTACAO_USUARIO_NAO_ENCONTRADA,
	FORNECEDOR_JA_COTOU_PEDIDO,
	PEDIDO_SEM_ITENS_PARA_COTACAO,
	ITEM_COTADO_NAO_PERTENCE_PEDIDO,
	ITEM_COTADO_DUPLICADO,
	TODOS_ITENS_DEVEM_SER_COTADOS,
	TOTAL_COTACAO_INVALIDO;

	/* @formatter:on */

}
